#!/usr/bin/env python3
"""Collect @cite markers from the suite and check them against the bibliography.

Same shape as tools/gmem_audit.py: the declaration lives in a comment next to
the code it describes, a file of record holds the definitions, and this fails
when the two disagree. A citation that sits in a separate document nobody edits
goes stale the moment the code moves; one that sits on the line it belongs to
moves with it.

Marker syntax, anywhere in a .jsfx / .jsfx-inc / .lua comment:

    // @cite <key> -- <what it is used for here>
    -- @cite <key> -- <what it is used for here>

Usage:
    python tools/cite_audit.py            # report, non-zero exit on a problem
    python tools/cite_audit.py --write    # also regenerate CITATIONS.md
"""

import argparse
import os
import re
import sys
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BIB = os.path.join(ROOT, "references", "BIBLIOGRAPHY.md")
OUT = os.path.join(ROOT, "CITATIONS.md")

CITE = re.compile(r"@cite\s+([a-z0-9][a-z0-9._-]*)\s*(?:--\s*(.*))?$")
KEY = re.compile(r"^\*\*`([a-z0-9][a-z0-9._-]*)`\*\*\s*(?:[-—]+\s*`(\w+)`)?")
EXTS = (".jsfx", ".jsfx-inc", ".lua", ".py")
SKIP = {".git", "node_modules", "__pycache__"}


def bibliography():
    """key -> (status, first line of the entry)."""
    entries = {}
    if not os.path.exists(BIB):
        return entries
    with open(BIB, encoding="utf-8", errors="replace") as fh:
        lines = fh.readlines()
    section = ""
    for i, line in enumerate(lines):
        if line.startswith("## "):
            section = line[3:].strip()
        m = KEY.match(line.strip())
        if m:
            title = ""
            for nxt in lines[i + 1:i + 3]:
                if nxt.strip():
                    title = nxt.strip()
                    break
            entries[m.group(1)] = (m.group(2) or "unmarked", title, section)
    return entries


def scan():
    """key -> [(relpath, lineno, note)]"""
    hits = defaultdict(list)
    for base, dirs, files in os.walk(ROOT):
        dirs[:] = [d for d in dirs if d not in SKIP]
        for f in sorted(files):
            if not f.endswith(EXTS):
                continue
            path = os.path.join(base, f)
            rel = os.path.relpath(path, ROOT).replace("\\", "/")
            if rel.startswith("tools/cite_audit"):
                continue
            with open(path, encoding="utf-8", errors="replace") as fh:
                for n, line in enumerate(fh, 1):
                    m = CITE.search(line)
                    if m:
                        hits[m.group(1)].append((rel, n, (m.group(2) or "").strip()))
    return hits


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true",
                    help="regenerate CITATIONS.md from the markers")
    args = ap.parse_args()

    bib = bibliography()
    hits = scan()
    problems = 0

    print("=" * 68)
    print("CITATIONS")
    print("=" * 68)
    if not bib:
        print("  ! no bibliography at references/BIBLIOGRAPHY.md")
        return 1

    for key in sorted(bib):
        status, title, section = bib[key]
        sites = hits.get(key, [])
        code_expected = section != "Samples"
        flag = "" if sites or not code_expected else "   <- cited by nothing"
        if not sites and code_expected:
            problems += 1
        print("\n  %-32s %-11s %d site(s)%s" % (key, status, len(sites), flag))
        print("      %s" % title[:88])
        for rel, n, note in sites:
            print("      %s:%d%s" % (rel, n, ("  " + note) if note else ""))

    unknown = sorted(set(hits) - set(bib))
    if unknown:
        problems += len(unknown)
        print("\n" + "=" * 68)
        print("CITED IN CODE BUT NOT IN THE BIBLIOGRAPHY")
        print("=" * 68)
        for key in unknown:
            print("  %s" % key)
            for rel, n, note in hits[key]:
                print("      %s:%d" % (rel, n))

    unverified = [k for k, v in bib.items() if v[0] == "unverified"]
    print("\n" + "-" * 68)
    print("  %d source(s), %d marker(s) in code, %d unverified"
          % (len(bib), sum(len(v) for v in hits.values()), len(unverified)))
    if unverified:
        print("  unverified: " + ", ".join(sorted(unverified)))
        print("  (present in the code, but which paper it came from is not"
              " established -- confirm or drop, do not leave it looking sure)")

    if args.write:
        with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
            fh.write("# Citations\n\n")
            fh.write("Generated by `tools/cite_audit.py --write`. Do not edit"
                     " by hand -- add a `@cite` marker in the source and an"
                     " entry in `references/BIBLIOGRAPHY.md`.\n\n")
            for key in sorted(bib):
                status, title, _sec = bib[key]
                sites = hits.get(key, [])
                fh.write("## %s\n\n%s\n\n" % (key, title))
                if status == "unverified":
                    fh.write("*Attribution unconfirmed — the technique is in"
                             " the code, the source is not established.*\n\n")
                if sites:
                    fh.write("Used at:\n\n")
                    for rel, n, note in sites:
                        fh.write("- `%s:%d`%s\n" % (rel, n, (" — " + note) if note else ""))
                    fh.write("\n")
        print("\n  wrote %s" % os.path.relpath(OUT, ROOT))

    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
